import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function CaucionPage() {
  return <h1>Caución</h1>;
}