import type { Metadata } from "next";
import { CaucionQuoterForm } from "../../components/quoter-form/caucion-quoter-form.component";

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function CaucionPage() {
  return (
    <section className="px-4 md:px-16 justify-end flex flex-1 py-10 min-h-[calc(100vh-96px)] bg-caucion-img bg-light_primary">
      <CaucionQuoterForm />
    </section>
  );
}